blank_issues_enabled: true
contact_links:
    - name: Start a discussion
      url: https://github.com/danburzo/percollate/discussions/
      about: For questions and answers, please use the Discussions area.
